### ISSUE TITLE
ReflectionException: "Class firewall.config does not exist" after upgrading antonioribeiro/support to v0.3.3

### ISSUE THREAD

**Issue by hackel** [antonioribeiro/firewall#10]
I encountered this error trying to run an artisan migrate.  It seems unable to find the Firewall facade in Firewall::getMigrator()->up().  Downgrading to antonioribeiro/support v0.3.2 allowed the migration to run fine.  Note: I'm running Laravel 4.1.

Here is the exception trace:

    () at /vendor/laravel/framework/src/Illuminate/Container/Container.php:501
    ReflectionClass->__construct() at /vendor/laravel/framework/src/Illuminate/Container/Container.php:501
    Illuminate\Container\Container->build() at /vendor/laravel/framework/src/Illuminate/Container/Container.php:425
    Illuminate\Container\Container->make() at /vendor/laravel/framework/src/Illuminate/Foundation/Application.php:463
    Illuminate\Foundation\Application->make() at /vendor/laravel/framework/src/Illuminate/Container/Container.php:809
    Illuminate\Container\Container->offsetGet() at /vendor/pragmarx/firewall/src/Vendor/Laravel/ServiceProvider.php:153
    PragmaRX\Firewall\Vendor\Laravel\ServiceProvider->PragmaRX\Firewall\Vendor\Laravel\{closure}() at /vendor/laravel/framework/src/Illuminate/Container/Container.php:207
    Illuminate\Container\Container->Illuminate\Container\{closure}() at /vendor/laravel/framework/src/Illuminate/Container/Container.php:498
    Illuminate\Container\Container->build() at /vendor/laravel/framework/src/Illuminate/Container/Container.php:425
    Illuminate\Container\Container->make() at /vendor/laravel/framework/src/Illuminate/Foundation/Application.php:463
    Illuminate\Foundation\Application->make() at /vendor/laravel/framework/src/Illuminate/Container/Container.php:809
    Illuminate\Container\Container->offsetGet() at /vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:146
    Illuminate\Support\Facades\Facade::resolveFacadeInstance() at /vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:116
    Illuminate\Support\Facades\Facade::getFacadeRoot() at /vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:200
    Illuminate\Support\Facades\Facade::__callStatic() at /app/database/migrations/2014_11_13_013053_create_firewall_tables.php:16
    PragmaRX\Firewall\Vendor\Laravel\Facade::getMigrator() at /app/database/migrations/2014_11_13_013053_create_firewall_tables.php:16
    CreateFirewallTables->up() at /vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:133
    Illuminate\Database\Migrations\Migrator->runUp() at /vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:109
    Illuminate\Database\Migrations\Migrator->runMigrationList() at /vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:80
    Illuminate\Database\Migrations\Migrator->run() at /vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php:65
    Illuminate\Database\Console\Migrations\MigrateCommand->fire() at /vendor/laravel/framework/src/Illuminate/Console/Command.php:108
    Illuminate\Console\Command->execute() at /vendor/symfony/console/Symfony/Component/Console/Command/Command.php:241
    Symfony\Component\Console\Command\Command->run() at /vendor/laravel/framework/src/Illuminate/Console/Command.php:96
    Illuminate\Console\Command->run() at /vendor/symfony/console/Symfony/Component/Console/Application.php:887
    Symfony\Component\Console\Application->doRunCommand() at /vendor/symfony/console/Symfony/Component/Console/Application.php:191
    Symfony\Component\Console\Application->doRun() at /vendor/symfony/console/Symfony/Component/Console/Application.php:121
    Symfony\Component\Console\Application->run() at /artisan:59

**Comment by antonioribeiro** [comment]
Not happening anymore with support 0.3.5.
