### ISSUE TITLE
possible duplicate cache value

### ISSUE THREAD

**Issue by meyer59** [antonioribeiro/firewall#100]
Hi 
What is the difference in these two cache value in the config/firewall.php file ?
https://github.com/antonioribeiro/firewall/blob/c33b9e593e02c6d80e776abd85a45b69d18c87ac/src/config/config.php#L72
https://github.com/antonioribeiro/firewall/blob/c33b9e593e02c6d80e776abd85a45b69d18c87ac/src/config/config.php#L80

**Comment by antonioribeiro** [comment]
First one is general IP cache, when someone searches for an IP address, it caches that search for some time. Finding an IP address contained in a CIDR range (172.17.0.0/24, for instance) can be a "slow", caching it improves performance. 

Second one is list cache. Sometimes a database list can take some time to load and process, caching it, if you are not making frequent changes to your lists, may improve firewall speed a lot.

**Comment by meyer59** [comment]
Got it. I will add those comments to my config/firewall.php. Thank you

**Comment by antonioribeiro** [comment]
Will add to the package config too, thank you.
