### ISSUE TITLE
Incompatible syntax with php 5.6 in 1.x versions

### ISSUE THREAD

**Issue by tolnaiz** [antonioribeiro/firewall#102]
On PHP 5.6 this line gives a parse error because the assignment is not allowed in between the parentheses.

`$success = ($updater = new GeoIpUpdater)->updateGeoIpFiles($this->config->get('geoip_database_path'));`

I created a fix, but I cannot create a pull request for the 1.x version.

https://github.com/ferling/firewall/commit/ef93d5a4636a2f25f72937c4068df4ca41eb2b3f

**Comment by antonioribeiro** [comment]
This is not 1.x code, this is more like 2.x

**Comment by antonioribeiro** [comment]
This is probably why you cannot send a pull request to 1.x

**Comment by tolnaiz** [comment]
As I see, it is in v1.1.0:
https://github.com/antonioribeiro/firewall/blob/v1.1.0/src/Firewall.php#L521

**Comment by antonioribeiro** [comment]
Should be fixed on v1.1.1. You just have to update.
Thank you!
