### ISSUE TITLE
How to add ipaddress to the database firewall table?

### ISSUE THREAD

**Issue by githubgobi** [antonioribeiro/firewall#120]
How to add ipaddress to the firewall table?how to update whitelisted&blocklisted?

**Comment by fatemejon** [comment]
in laravel  and add to blacklist :

 $ip        = Input::get('ip');
 $valid     = filter_var($ip, FILTER_VALIDATE_IP);

$firewall  = app()->make('firewall');
$return = $firewall->blacklist($valid);

**Comment by githubgobi** [comment]
thank You @fatemejon 

But have to add ip address to database use
