### ISSUE TITLE
Whitelisted ips and still get blocked

### ISSUE THREAD

**Issue by meyer59** [antonioribeiro/firewall#122]
Hi
I have a bunch of whitelisted ip in the conf 
![image](https://user-images.githubusercontent.com/9505463/38678946-c25f28f8-3e62-11e8-8120-e913ab96ad6b.png)

but i still get blocked by the `attack_blocker` when i go above the `allowed_frequency`
Hope anyone can help me, Thanks

**Comment by mndeto** [comment]
Seems like Whitelisting is not working in localhost but okay in a client-server environment.

**Comment by meyer59** [comment]
I have the issue even if i’m not as localhost, with the first ip in the screenshot 82.64...

**Comment by antonioribeiro** [comment]
Should be fixed in the next release.
