### ISSUE TITLE
Reversed negation

### ISSUE THREAD

**Issue by meyer59** [antonioribeiro/firewall#126]
Hi,
I am getting blocked even if my ip is whitelisted. 
At this point, it seems like this should be inversed with a negation. 
`!` `$this->config()->get("attack_blocker.action.{$this->record[$type]['type']}.blacklist_whitelisted");`
The meaning: _To have a whitelisted Ip we should have the ip in the whitelisted array AND NOT having_ the `blacklist_whitelisted` option to true.
https://github.com/antonioribeiro/firewall/blob/ea54682c8d87f049818fb22c7524318c82e0f263/src/Support/AttackBlocker.php#L273
Anyone is running the smae issue ?

**Comment by antonioribeiro** [comment]
Should be fixed in the next release.
