### ISSUE TITLE
Laravel 5.7

### ISSUE THREAD

**Issue by jmichaelterenin** [antonioribeiro/firewall#132]
Hi Antonio,

First off, thank you for providing your firewall package, excellent work.
I've had your package since Laravel 5.0, but I have upgraded to 5.7.
I noticed your comment that it is not working in 5.7, what exactly is not working? The main aspect of this package, which is the blocking of attacks, I assume?

Do you have any timeline to bring the package up to speed with 5.7?

**Comment by antonioribeiro** [comment]
Should work from Laravel 5.x and 6.x
