### ISSUE TITLE
Notice: Undefined offset: 1 in IpAddress::cidrToRange

### ISSUE THREAD

**Issue by jordanade** [antonioribeiro/firewall#137]
/var/app/current/vendor/pragmarx/support/src/IpAddress.php in PragmaRX\Support\IpAddress::cidrToRange at line 232

**Comment by jordanade** [comment]
Anyone know a solution? This is filling up my logs.

**Comment by lk77** [comment]
I have the same error :
```
ErrorException: Notice: Undefined offset: 1
#68 /vendor/pragmarx/support/src/IpAddress.php(232): PragmaRX\Support\IpAddress::cidrToRange
#67 /vendor/pragmarx/support/src/IpAddress.php(283): PragmaRX\Support\IpAddress::ipV4Valid
```

**Comment by rydje** [comment]
I had the same issue. To fix it I turned the flag 'enable_range_search' to false.
It's used in the validRange method called from checkSecondaryLists method.

I'm not using cidr notation on my addresses I don't need it for now so I does work for me.

**Comment by rdpascua** [comment]
I got the same issue above even though I disabled the `enable_range_search`

**Comment by decowboy** [comment]
I'm experiencing the same issue

**Comment by decowboy** [comment]
What seems to fix this issue for me is to not use any wildcards.
I changed my only firewall entry from _10.*.*.*_ to _10.0.0.0/8_, and I haven't gotten the warning since.
I haven't tested it enough to be sure though.

What I do know is my stacktrace shows the warning occurred in:
`/vendor/pragmarx/support/src/IpAddress.php in PragmaRX\Support\IpAddress::cidrToRange at line 232`
`$cidr = explode('/', $cidr);
$range[0] = long2ip((ip2long($cidr[0])) & ((-1 << (32 - (int)**$cidr[1]**))));`

**Comment by rdpascua** [comment]
We'll im not using any wildcards :'( I'm using filter by country

**Comment by decowboy** [comment]
I created a pull request that should take care of the issue.

**Comment by nachete1987** [comment]
I have configured the 'enable_range_search' => false, and continue with this error :(

ErrorException: Notice: Undefined offset: 1
#84 /vendor/pragmarx/support/src/IpAddress.php(232): PragmaRX\Support\IpAddress::cidrToRange
#83 /vendor/pragmarx/support/src/IpAddress.php(283): PragmaRX\Support\IpAddress::ipV4Valid
#82 /vendor/pragmarx/firewall/src/Support/IpAddress.php(20): PragmaRX\Firewall\Support\IpAddress::isValid

**Comment by nachete1987** [comment]
I think that the problem is support dependency version.
When firewall package is downloaded, old Support version is downloaded because 857e250 commit content is not downloaded.
