### ISSUE TITLE
Country not blocked

### ISSUE THREAD

**Issue by imchivaa** [antonioribeiro/firewall#139]
Hi,

First of all, thanks for creating and mainting this package. I have a problem when enabling country blocking. 

It's fine when i block country:my since i am from malaysia. This prevent me from accessing the routes (403). But when i block example: country:ca, and i use vpn like tunnel bear to canada and access my site, it's accessible. 

Not only canada, i tried few different countries and other vpn as well. The results are the same, can explain if i missed out anything or any steps?

Thank you.

**Comment by antonioribeiro** [comment]
You are probably using geoip or geoip2 to detect the country, so maybe it's not working because it doesn't support VPN? Or the VPN you are using is not doing a very good making you look like you are not in your country anymore?

Please try some help in here: https://github.com/maxmind/GeoIP2-php
