### ISSUE TITLE
website behind Cloudflare not block because IP is not detected properly

### ISSUE THREAD

**Issue by nachete1987** [antonioribeiro/firewall#156]
When the website is behind cloudflare, the IP that is recived in $firewall->getIp() is the cloudflare IP.
I resolve it with the following code in '/pragmarx/firewall/src/Filters/Blacklist.php'

if ($firewall->isBlacklisted($ipAddress = isset($_SERVER["HTTP_CF_CONNECTING_IP"])? $_SERVER["HTTP_CF_CONNECTING_IP"] : $request->ip())) {

**Comment by antonioribeiro** [comment]
Should be fixed in the next version.
