### ISSUE TITLE
Uncaught exception 'ReflectionException' with message 'Class log does not exist'...

### ISSUE THREAD

**Issue by lucasromanojf** [antonioribeiro/firewall#17]
This error occurs on a Laravel 5 project when running "composer update"

![image](https://cloud.githubusercontent.com/assets/3661610/6250004/1e4eacf4-b772-11e4-99cc-196cf37eb8dd.png)

If I remove the package from composer.json and run "composer update" again, the error does not occur anymore

**Comment by antonioribeiro** [comment]
Check if your Laravel 5 .env file is in place, please.

**Comment by lucasromanojf** [comment]
Yes, it is. This error does not occur on dev-master.

**Comment by antonioribeiro** [comment]
Yeah, I fixed it (environment) on dev-master, but I can't tag it right away because of the support package used by other packages...

**Comment by lucasromanojf** [comment]
Ok, no problem, I'll keep using dev-master for now, thank you so much!

**Comment by antonioribeiro** [comment]
I just tagged them 0.5.0. Should work on stable now.
