### ISSUE TITLE
Php artisan firewall:list doesn't work 

### ISSUE THREAD

**Issue by ninijule** [antonioribeiro/firewall#171]
Hello, 
i have a problem with the firewall because i can't list and use the command in the documentation.
I installed Firewall with composer. 
I run migration.
I have this when i try to launch php artisan firewall:list
![image](https://user-images.githubusercontent.com/27823056/93001967-78f9de80-f533-11ea-970c-81c0b428c1e9.png)
![image](https://user-images.githubusercontent.com/27823056/93001996-a181d880-f533-11ea-9e62-905d1f016229.png)

I registered all in the middleware but nothing happens in the console.

<?php

namespace App\Http;

use Illuminate\Foundation\Http\Kernel as HttpKernel;

class Kernel extends HttpKernel
{
    /**
     * The application's global HTTP middleware stack.
     *
     * These middleware are run during every request to your application.
     *
     * @var array
     */
    protected $middleware = [
        // \App\Http\Middleware\TrustHosts::class,
        \App\Http\Middleware\TrustProxies::class,
        \Fruitcake\Cors\HandleCors::class,
        \App\Http\Middleware\CheckForMaintenanceMode::class,
        \Illuminate\Foundation\Http\Middleware\ValidatePostSize::class,
        \App\Http\Middleware\TrimStrings::class,
        \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
    ];

    /**
     * The application's route middleware groups.
     *
     * @var array
     */
    protected $middlewareGroups = [
        'web' => [
            \App\Http\Middleware\EncryptCookies::class,
            \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
            \Illuminate\Session\Middleware\StartSession::class,
            // \Illuminate\Session\Middleware\AuthenticateSession::class,
            \Illuminate\View\Middleware\ShareErrorsFromSession::class,
            \App\Http\Middleware\VerifyCsrfToken::class,
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
        ],

        'api' => [
            'throttle:60,1',
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
        ],
        'firewall' => [
            \PragmaRX\Firewall\Middleware\FirewallBlacklist::class,
            \PragmaRX\Firewall\Middleware\BlockAttacks::class,
        ]
    ];

    /**
     * The application's route middleware.
     *
     * These middleware may be assigned to groups or used individually.
     *
     * @var array
     */
    protected $routeMiddleware = [
        'auth' => \App\Http\Middleware\Authenticate::class,
        'auth.basic' => \Illuminate\Auth\Middleware\AuthenticateWithBasicAuth::class,
        'bindings' => \Illuminate\Routing\Middleware\SubstituteBindings::class,
        'cache.headers' => \Illuminate\Http\Middleware\SetCacheHeaders::class,
        'can' => \Illuminate\Auth\Middleware\Authorize::class,
        'guest' => \App\Http\Middleware\RedirectIfAuthenticated::class,
        'password.confirm' => \Illuminate\Auth\Middleware\RequirePassword::class,
        'signed' => \Illuminate\Routing\Middleware\ValidateSignature::class,
        'throttle' => \Illuminate\Routing\Middleware\ThrottleRequests::class,
        'verified' => \Illuminate\Auth\Middleware\EnsureEmailIsVerified::class,
        'admin' => \App\Http\Middleware\Admin::class,
        'fw-only-whitelisted' => \PragmaRX\Firewall\Middleware\FirewallWhitelist::class,
        'fw-block-blacklisted' => \PragmaRX\Firewall\Middleware\FirewallBlacklist::class,
        'fw-block-attacks' => \PragmaRX\Firewall\Middleware\BlockAttacks::class,
    ];
}

Can you help me please :) ?
ty

**Comment by pvankouteren** [comment]
The middelware registration has nothing to do with the command not being able to run.
Can you run

```
php artisan
```

and get an overview of the commands?

You're using laravel? Which version?

**Comment by ritaorion** [comment]
The question is two years old here, but I had a similar issue the very first time I installed this. If you have the same problem as ninijule, just run `composer update`. That seemed to work for me.
