### ISSUE TITLE
php artisan firewall:tables  -> 'ErrorException' with message 'file_put_contents(... 

### ISSUE THREAD

**Issue by hawle** [antonioribeiro/firewall#18]
I am trying out this package, and during the install process, the php artisan firewall:tables command runs into an Exception. It seems that it is trying to put the migration file ona path that is L4 specific: 

exception 'ErrorException' with message 'file_put_contents(/home/vagrant/[APP_ROOT]/app/database/migrations/2015_02_18_185309_create_firewall_tables.php): failed to open stream: No such file or directory' in /home/vagrant/[APP_ROOT]/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:74

**Comment by antonioribeiro** [comment]
Yes, you may be right. Will look into it right now.

**Comment by hawle** [comment]
I could trace it down to this method: pragmarx/firewall/src/Vendor/Laravel/Artisan/Tables.php > createBaseMigration(). 

I think it is not giving the correct path for L5.

**Comment by antonioribeiro** [comment]
Should be fixed now.

**Comment by antonioribeiro** [comment]
Thank you!

**Comment by hawle** [comment]
Thanks, it is fine, but I can't update it, since you have `"pragmarx/support": "0.5.*@dev"` in firewall's composer.json. Composer won't update pragmarx/support which has the `isLaravel5()` method now.

**Comment by antonioribeiro** [comment]
It should be fine now.

**Comment by hawle** [comment]
Perfect! Working fine! Thank you!
