### ISSUE TITLE
Handling for use of both whitelist and blacklist in evaluation?

### ISSUE THREAD

**Issue by enygma** [antonioribeiro/firewall#19]
I glanced through the code and tried to figure out if there was anything in there for this, but didn't see it right off the bat. What happens if you get more complex with your needs and want to apply both the whitelist and blacklist to a route? From what I can tell right now, it's a "last in wins" kind of scenario - is this valid?

I could see someone wanting to, say, allow everyone from a specific subnet inside an organization to be able to view some data (maybe /user/view/1) but prevent others from viewing it. With the current setup it looks like that might just have to be some kind of nested route handling, but that seems like a bit of overkill.

**Comment by antonioribeiro** [comment]
I would say whitelist wins:

https://github.com/antonioribeiro/firewall/blob/master/src/Firewall.php#L154

So if you have 

    10.0.0.0/24 blacklisted

You can whitelist

    10.0.0.1 

And it will pass your filters. I tested it here to make sure it works :)

**Comment by enygma** [comment]
Ah, I missed that - thanks!
