### ISSUE TITLE
Behind load balancer / proxy

### ISSUE THREAD

**Issue by luoshiben** [antonioribeiro/firewall#24]
If the app is behind a load balancer or proxy then getClientIp() will return the IP address of the load balancer or proxy, not the IP address of the actual client. Is there a way to use x-forwarded-for or to setTrustedProxies() on the request used by the firewall? Maybe this should be a config option which is set on the request in the service provider. Any help would be appreciated.

**Comment by tuwannu** [comment]
+1 on this

**Comment by zawmyohtet** [comment]
+1, too.

**Comment by NazarenoL** [comment]
+1!

**Comment by Pandahisham** [comment]
+1

**Comment by manakor** [comment]
+1

**Comment by drtzack** [comment]
+1

**Comment by Lednerb** [comment]
+1

**Comment by Lednerb** [comment]
@antonioribeiro Do you have any news on this topic?

Just searched for around an hour until i've checked this issue.

**Comment by drtzack** [comment]
That package is so buggy and developer is not interested on it anymore.

**Comment by rdev5** [comment]
Have you guys not seen these?

- `Request::ip()` - http://stackoverflow.com/a/33268732/901156
- `getClientIp()` - https://github.com/symfony/http-foundation/blob/master/Request.php#L832
- `getClientIps()` - https://github.com/symfony/http-foundation/blob/master/Request.php#L78

0

**Comment by rdev5** [comment]
By the way, this is a library/package that I wouldn't mind supporting. There may be other/better implementations, but I've personally seen jury-rigged WAFs catch some of the most explicit and even targeted types of attacks (read application-specific).

Certainly no replacement for a commercial one, however. I would still strongly recommend vendors like CloudFlare; not as a replacement, though, but *in addition to* whatever you come up with specific to your organization.

**Comment by antonioribeiro** [comment]
Sorry for being so late here, but https://github.com/fideloper/TrustedProxy should work with Firewall in L5+.

**Comment by jaysonlane** [comment]
@antonioribeiro can you elaborate a little on how TrustedProxy solves this problem?
