### ISSUE TITLE
FatalErrorException Class 'PragmaRX\Firewall\Repositories\Firewall\Firewall' not found

### ISSUE THREAD

**Issue by saimiris** [antonioribeiro/firewall#33]
Hi Antonio,

I tried to use your component but I got one issue.

FatalErrorException in /Users/thomas/Development/Sites/Prof_Express_V2/vendor/pragmarx/firewall/src/Vendor/Laravel/ServiceProvider.php line 116:
Class 'PragmaRX\Firewall\Repositories\Firewall\Firewall' not found

Do you know how I can solve this problem?

Many thanks!

**Comment by saimiris** [comment]
When I launch the "php artisan firewall:list" command line, I actually the same kind of error:

[Symfony\Component\Debug\Exception\FatalErrorException]             
  Class 'PragmaRX\Firewall\Repositories\Firewall\Firewall' not found

**Comment by tuwannu** [comment]
Have you tried executing `php artisan clear-compiled` then `composer dump-autoload`?

**Comment by saimiris** [comment]
I solved it. I was not installing the component properly.
