### ISSUE TITLE
How to use database to store and destroy ip address for block or unblock

### ISSUE THREAD

**Issue by tux-world** [antonioribeiro/firewall#39]
Hi. Thanks to this package's owner. How to use database to store and destroy ip address for block or unblock? i want to learn about to save ip from back-end system managment and manage ip address. please help me to how to store ip address anf fetch theme. thanks

**Comment by antonioribeiro** [comment]
You have to enable database storage for your ip addresses, then just 

'''
php artisan firewall:clear
'''

If you want to delete them all. Or

'''
php artisan firewall:remove <ip address>
'''

To remove only one.

**Comment by tux-world** [comment]
That means database enabled by default?

**Comment by Khaled-AlSaeed** [comment]
in config file:

    /**
     * Should Firewall use the database?
     */

    'use_database' => true,

**Comment by dev-roshan** [comment]
'use_database' =>true, didnt do for me, Please help to save data, which method is used to save data?? Thanks.
