### ISSUE TITLE
getStubConfigPath undefined

### ISSUE THREAD

**Issue by RhenusoneRosalia** [antonioribeiro/firewall#42]
After installing the firewall with composer and adding the facades in the app.php

every artisan command, or page i view within my application returns 
[BadMethodCallException]  
Call to undefined method [getStubConfigPath]  

Here is a screenshot from my composer file
<img width="389" alt="schermafbeelding 2016-01-01 om 03 57 05" src="https://cloud.githubusercontent.com/assets/7961854/12069626/c4c0b600-b03b-11e5-868d-09156497f6ea.png">

**Comment by exwizzard** [comment]
I am having the same error on a fresh 5.2.7

**Comment by exwizzard** [comment]
It seems that it bundles some old version of the 'support' package from the same author.

I went and git cloned support into the app/vendor/pragmarx folder and everything works now.

**Comment by rohan0793** [comment]
@exwizzard Could you elaborate what you exactly did to resolve this?

**Comment by mrgswift** [comment]
@rohan0793:  I had a similar issue. For some reason the support package version bundled is an older version and I found that forcing the latest version of the support package in my composer.json fixed the problem.

**Comment by exwizzard** [comment]
@rohan0793 Yeah you can just force install the support package and that would work.

**Comment by rohan0793** [comment]
It works like a charm now. Thank you.

**Comment by antonioribeiro** [comment]
This: `"pragmarx/support": "~0.6.6"`

Usually means any version above this one starting with 0.6.

This is what I just got here changing nothing.

![image](https://cloud.githubusercontent.com/assets/3182864/21469129/68458372-ca22-11e6-93af-f7e5048b2606.png)

**Comment by antonioribeiro** [comment]
Bumped it o 0.6.12 anyways...
