### ISSUE TITLE
can't get IPs from a file

### ISSUE THREAD

**Issue by zorx** [antonioribeiro/firewall#43]
it seems that we can't use this feature :

```
'blacklist' => array(
    '/path/to/dir/blacklisted.txt',
)
```

**Comment by yaroslav-pavlenko** [comment]
In method `Firewall->getIpsFromAnything()` function `IpAddress::ipV4Valid` converts this line to `['0.0.0.0','255.255.255.255']`.

**Comment by tux-world** [comment]
can you help me to read ip list from database?

**Comment by antonioribeiro** [comment]
Should be fixed now.
