### ISSUE TITLE
Error: The helper "table" not defined

### ISSUE THREAD

**Issue by kinnngg** [antonioribeiro/firewall#46]
When run `php artisan firewall:list` I got this error

```
[Symfony\Component\Console\Exception\InvalidArgumentException]
  The helper "table" is not defined.
```

Laravel 5.2

**Comment by brianmclachlin** [comment]
Having the same issue in 5.2

**Comment by liucf** [comment]
@antonioribeiro Having the same issue in 5.2???

**Comment by vitsw** [comment]
Having the same issue in 5.2

**Comment by olde86** [comment]
Having the same issue 5.2

**Comment by antonioribeiro** [comment]
I could not reproduce it. Please take a look at this boostrap app to see it working in full:

https://github.com/antonioribeiro/pragmarx.com
