### ISSUE TITLE
Matching non-database IP always matches country code

### ISSUE THREAD

**Issue by AndyDunn** [antonioribeiro/firewall#51]
It looks like the following code is always matching the first results in the array listing of IP address and countries using the config file (not database), even though it shouldn't.

https://github.com/antonioribeiro/firewall/blob/master/src/Repositories/Firewall/Firewall.php

```
private function ipArraySearch($ip, $ips)
    {
        foreach($ips as $key => $value)
        {
            if (
                (isset($value['ip_address']) && $value['ip_address'] == $ip) ||
                ($key == $ip) ||
                ($value == $ip)
            )
            {
                return $value;
            }
        }
        return false;
    }
```

Changing:

`($key == $ip) ||`

To:

`(strval($key) == $ip) ||`

Will fix it and only return the appropriate result.

**Comment by antonioribeiro** [comment]
PR was merged. Thank you.
