### ISSUE TITLE
Setting ip_list_cache_expire_time breaks firewall:list command

### ISSUE THREAD

**Issue by jamesggordon** [antonioribeiro/firewall#52]
If you set the `ip_list_cache_expire_time` variable in the configuration file to something other than zero, **php artisan firewall:list** no longer works.

The reason is because firewall:list uses the the _all()_ method in the Firewall class and the first thing the _all()_ method does is this:

```
public function all()
{
    $cacheTime = $this->config->get('ip_list_cache_expire_time');

    if ($cacheTime && $this->cache->has(static::IP_ADDRESS_LIST_CACHE_NAME))
    {
        return $this->cache->get(static::IP_ADDRESS_LIST_CACHE_NAME);
    }
...
```

I'm not sure what this has to do with returning the list of currently blacklisted/whitelisted IP addresses. I would lodge a PR except this code looks so deliberate that I'm sure I'm missing something and I don't want to break some other behaviour that was intended.

I discovered this issue when I accidentally set `ip_list_cache_expire_time` instead of `cache_expire_time`. Once I set `ip_list_cache_expire_time` back to zero, the firewall:list function worked again.

**Comment by jamesggordon** [comment]
Just realised I might be on an old branch...

**Comment by antonioribeiro** [comment]
I just enabled it, and it works:

![image](https://cloud.githubusercontent.com/assets/3182864/21469003/679d1852-ca1a-11e6-9f88-c9a9d944a6d1.png)

Is this still valid?

**Comment by jamesggordon** [comment]
I tested again and now realise that the problem lies in my understanding of how the caching has been designed. I have hunted through the other issues but cannot find any more details on the caching.

Would you mind providing a brief overview on how the caching works and, specifically, the two configuration options `cache_expire_time` and `ip_list_cache_expire_time`?

Thanks in advance.
