### ISSUE TITLE
can't use artisan commands in latest version

### ISSUE THREAD

**Issue by vesper8** [antonioribeiro/firewall#54]
Using the latest 1.0.3 and Laravel 5.2.45. Following all your installation instructions.

Firewall is working for blocking single IPs

Only artisan commands available are "tables" and "list". Cannot use clear, whitelist or blacklist.

Have added countries to block manually to the firewall.php config file. I've added a large list of countries on individual line. Even if I uncomment the country I am testing access from, it always blocks me. No caches are enabled. It always blocks me if I have country search enabled.

Any chance for an update?

**Comment by vesper8** [comment]
Please note that applying fix in #51 fixes the issue with every IP being blocked when using the country search.

Could you please make that new commit? I changed it inside the vendor folder but I'm worried it's going to break again when composer update is run at some point

**Comment by antonioribeiro** [comment]
Other commands are available only if you are using database.

    /**
     * Should Firewall use the database?
     */

    'use_database' => true,

So you have to `vendor:publish` it before using it too.

and this was also merged: https://github.com/antonioribeiro/firewall/pull/55
