### ISSUE TITLE
Compatibility with route caching

### ISSUE THREAD

**Issue by profxp** [antonioribeiro/firewall#58]
Hi there,

I use your excellent plugin. Now I would like to to do route caching https://laravel.com/docs/5.1/controllers#route-caching but after doing so, it seems that the route cache completely ignores the Firewall rules set-up in the routes file.
Is there a way to make Firewall plugin compatible with route caching?

Thanks.

**Comment by CODEheures** [comment]
Firewall + route caching work fine for me (Laravel 5.3)
Are you use Route group & middlware?
```
Route::group(['middleware' => 'fw-allow-wl'], function () {
    Route::get('/', 'CommonController@portal')->name('portal');
    Route::get('etc...',...);
});
```

**Comment by antonioribeiro** [comment]
Also working on Laravel 5.1:

![image](https://user-images.githubusercontent.com/3182864/29489920-8e5f7f86-8502-11e7-9233-8c70e4c2951d.png)

Using:

```php
Route::group(['middleware' => 'fw-block-bl'], function ()
{
    Route::get('/', 'Home@index');
});
```
