### ISSUE TITLE
Compatibility with 5.4 - method share was removed

### ISSUE THREAD

**Issue by eugensuvorov** [antonioribeiro/firewall#59]
Command  php artisan optimize returns following errors

```
  [Symfony\Component\Debug\Exception\FatalErrorException]
  Call to undefined method Illuminate\Foundation\Application::share()


Script php artisan optimize handling the post-update-cmd event returned with error code 255
```

There is an explanation https://laracasts.com/discuss/channels/laravel/undefined-method-illuminatefoundationapplicationshare-when-upgrading-to-laravel-54

Method **share** has been removed and should be replaced with the **singleton**.

**Comment by antonioribeiro** [comment]
Should be fixed now.
