### ISSUE TITLE
Breaks in production with Laravel 5.3.30

### ISSUE THREAD

**Issue by RobvH** [antonioribeiro/firewall#62]
Steps to reproduce:

```
composer create-project laravel/laravel l53test 5.3.30
edit .env set to production and debug = false
composer require pragmarx/firewall
php artisan // boom
```

`PHP Fatal error:  Cannot declare interface Illuminate\Contracts\Container\Container, because the name is already in use in {dir}/bootstrap/cache/compiled.php on line 4`

Does not break if Laravel 5.3.16 is installed this way, so there's a conflict/regression somewhere.

**Comment by csakshaug** [comment]
@RobvH Did you solve it?

**Comment by charlieprynn** [comment]
Has this still not been resolved?

**Comment by zupolgec** [comment]
I've used this package today for the first time, same problem in production with Laravel 5.2.39

**Comment by RobvH** [comment]
No, still unsolved, we just locked our version of the failing dependency back to a non-failing version until we updated the project to L5.4.  Used Shift and highly recommend it.

**Comment by antonioribeiro** [comment]
Should be fixed now.: https://github.com/antonioribeiro/support/commit/426a60953e70a9d715648ff1b9b4684e55d385b9
