### ISSUE TITLE
PHP Parse error:  syntax error, unexpected '->' (T_OBJECT_OPERATOR) in vendor\pragmarx\firewall\src\Firewall.php on line 584

### ISSUE THREAD

**Issue by jmichaelterenin** [antonioribeiro/firewall#77]
Getting this error when attempting to perform:
php artisan firewall:tables   (no problems)
php artisan migrate (error occurs)

I assumed you were referencing the geoip2/geoip2 package, even though you state that it's optional in the documentation, so I required it in my composer, performed a composer update, dump-autoload, and returning to the migration step, I still get the error.

Can you assist? Thanks

**Comment by antonioribeiro** [comment]
Which version are you using?

**Comment by jmichaelterenin** [comment]
Hi Antonio,
Sorry for not including: 
Laravel 5.4, 
"pragmarx/firewall" : "^2.0",
"geoip2/geoip2" : "~2.0",

**Comment by antonioribeiro** [comment]
Line 584 related to the updategeoip command

![image](https://user-images.githubusercontent.com/3182864/29734347-132e44bc-89c8-11e7-92e4-07eebde63b81.png)

And it is not executed elsewhere.

**Comment by jmichaelterenin** [comment]
Sure, I saw that, but I'm sorry, I'm unfamiliar with the Geoip package, not sure what that means, I don't even plan on using any country blacklisting, just ip address ...

**Comment by antonioribeiro** [comment]
So, the problem was during "artisan migrate" or "artisan firewall:updategeoip"?

Could you, please send us the whole error message, and the call stack? Should appear in your laravel.log

**Comment by jmichaelterenin** [comment]
`[2017-08-25 12:13:56] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '->' (T_OBJECT_OPERATOR)' in C:\xampp\htdocs\explore\vendor\pragmarx\firewall\src\Firewall.php:584
Stack trace:
#0 {main}  `

occurs with "artisan migrate"

**Comment by antonioribeiro** [comment]
You get nothing in `storage/logs/laravel.log`?

**Comment by jmichaelterenin** [comment]
Hi Antonio,
What is highlighted in code (with the time stamp), is what I get in laravel.log

**Comment by antonioribeiro** [comment]
So files must have not downloaded as they should. Try to remove vendor/pragmarx and then

    composer update

again

**Comment by jmichaelterenin** [comment]
ok, I'll let you know if it gets resolved with a fresh download, thanks

**Comment by justplayingames** [comment]
I see the same error

php version 5.6.24
pragmarx/firewall version": "v1.1.0",

It acts a syntax error.  I get the error when attempting to serve my index page using php artisan serve.  This route is using the firewall package.

A quick fix was to change line 521 to do it in two lines:

    $updater = new GeoIpUpdater;
    $success = $updater->updateGeoIpFiles($this->config->get('geoip_database_path'));

**Comment by antonioribeiro** [comment]
Just tagged version 2.0.2.

Thank you all.

**Comment by jmichaelterenin** [comment]
@justplayingames Thank you for assisting
@antonioribeiro AOK now, thanks!

**Comment by attaullah5130** [comment]
Duplicate of #
