### ISSUE TITLE
IP Addresses not being cached

### ISSUE THREAD

**Issue by hackel** [antonioribeiro/firewall#9]
I'm running 0.2.0 on Laravel 4.1. I have set 'cache_expire_time' => 60 in my config, but I am still seeing a firewall DB hit on every single request.  I'm using the Laravel memcached cache driver, which is working fine for in the rest of my application.  Not sure if this is a bug or if I could have missed something.

**Comment by antonioribeiro** [comment]
Maybe because it was still checking for lists of IP in the database in some cases. I just added a cache for that one too. Will be avaible in the next version, which should be out today.
